name: Python CI

on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Report
        run: |
          pip install coverage pytest-cov
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests  # Optional
          name: codecov-umbrella  # Optional
          fail_ci_if_error: true  # Optional

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code Review Scoring
        run: find . -path ./tests -prune -o -name '*.py' -print -exec pylint {} \;
      - name: Analysing code with PyLint
        run: |
          pylint $(find . -path ./tests -prune -o -name '*.py' -print) --fail-under=8.0
