name: Python CI

on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.11'
          environment-file: environment.yml
          activate-environment: ci-env

      - name: Install Dependencies
        run: |
          conda install --file requirements.txt

      - name: Generate Report
        run: |
          pip install coverage pytest-cov
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests  # Optional
          name: codecov-umbrella  # Optional
          fail_ci_if_error: true  # Optional

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.11'
          environment-file: environment.yml
          activate-environment: ci-env

      - name: Code Review Scoring
        run: find . -name '*.py' -print -exec pylint {} \;
      - name: Analysing code with PyLint
        run: |
          pylint $(find . -path ./tests -prune -o -name '*.py' -print) --fail-under=8.0
